### ISSUE TITLE
platypus error when trying to merge VCF

### ISSUE THREAD

**Issue by tdelhomme** [andyrimmer/Platypus#68]
Hi,

I get an error when ran platypus on one particular BAM file from TCGA:

```
2017-10-11T09:51:30.785112298Z 2017-10-11 09:51:30,784 - INFO - Merging output VCF file(s) into final file C345.TCGA-CJ-4901-11A-01D-1429-08.6_gdc_realn_platypus.vcf
2017-10-11T09:51:34.275662270Z Traceback (most recent call last):
2017-10-11T09:51:34.275684729Z File "/Platypus/bin/Platypus.py", line 46, in <module>
2017-10-11T09:51:34.275689365Z possCommands[command](sys.argv[2:])
2017-10-11T09:51:34.275698137Z File "/Platypus/bin/runner.py", line 600, in callVariants
2017-10-11T09:51:34.275701092Z runVariantCaller(options)
2017-10-11T09:51:34.275703645Z File "/Platypus/bin/runner.py", line 504, in runVariantCaller
2017-10-11T09:51:34.275706301Z mergeVCFFiles(fileNames, options.output, log)
2017-10-11T09:51:34.275708878Z File "/Platypus/bin/runner.py", line 344, in mergeVCFFiles
2017-10-11T09:51:34.275712598Z nextFile.next()
2017-10-11T09:51:34.275715118Z File "/Platypus/bin/runner.py", line 111, in next
2017-10-11T09:51:34.275717682Z pos = int(cols[1])
2017-10-11T09:51:34.275720194Z IndexError: list index out of range
```

Does any one already see this?

Thanks!

**Comment by tdelhomme** [comment]
I just have checked the BAM file for possible corruption with `picard validateSamFile` and the result is `no errors found`.
